name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Sync dependencies from pyproject.toml
        run: |
          rye sync

      - name: Run tests with pytest
        run: rye run pytest

      - name: Run Ruff
        run: rye run ruff check .

      - name: Run Mypy
        run: rye run mypy .
